version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "androidApp/build.gradle.kts" }}

      - run:
          name : Enable google services
          command: echo $GOOGLE_SERVICES | base64 -di > androidApp/google-services.json
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Build iOS
          command: ./gradlew :shared:compileKotlinIosX64

      - run:
          name: Build web
          command: ./gradlew :web:assemble

      - run:
          name: Build debug apk
          command: ./gradlew assembleDebug

      - run:
          name: Build test apk
          command: ./gradlew :androidApp:assembleDebugAndroidTest

      - run:
          name: Test
          command: ./gradlew test

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "androidApp/build.gradle.kts" }}

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results
